// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/base64"
	"fmt"
	"io"
	"strconv"
	"strings"

	"entgo.io/bug/ent/user"
	"entgo.io/contrib/entgql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/hashicorp/go-multierror"
)

const (
	typeUser = "user"
)

// GlobalID is a global unique identifier that contains a a type and id.
type GlobalID struct {
	Type, ID     string
	resolvedType interface{}
}

var marshalGlobalID = func(g GlobalID) string {
	id := fmt.Sprintf("%s:%s", g.Type, g.ID)
	return base64.StdEncoding.EncodeToString([]byte(id))
}

var unmarshalGlobalID = func(v interface{}) (string, string, error) {
	id := v.(string)
	b, err := base64.URLEncoding.DecodeString(id)
	if err != nil {
		return "", "", err
	}
	tid := strings.Split(string(b), ":")
	if len(tid) != 2 {
		return "", "", fmt.Errorf("invalid global identifier format %q", b)
	}

	return tid[0], tid[1], nil
}

// UnmarshalGQL implements the interface graphql.Unmarshaler.
func (g *GlobalID) UnmarshalGQL(v interface{}) error {
	typ, id, err := unmarshalGlobalID(v)
	if err != nil {
		return err
	}
	g.Type = typ
	g.ID = id

	switch g.Type {
	case typeUser:
		rt, err := strconv.Atoi(g.ID)
		if err != nil {
			return err
		}
		g.resolvedType = rt
		return nil
	}
	return fmt.Errorf("could not unmarshal the Global ID")
}

// MarshalGQL implements the interface graphql.Marshaler.
func (g GlobalID) MarshalGQL(w io.Writer) {
	_, _ = w.Write([]byte(strconv.Quote(g.String())))
}

func (g GlobalID) String() string {
	return marshalGlobalID(g)
}

func (g *GlobalID) Int() int {
	return g.resolvedType.(int)
}

func GlobalIDsPtrToInts(ids []*GlobalID) []int {
	r := make([]int, 0, len(ids))
	for i := range ids {
		r = append(r, ids[i].Int())
	}
	return r
}

func GlobalIDsToInts(ids []GlobalID) []int {
	r := make([]int, 0, len(ids))
	for i := range ids {
		r = append(r, ids[i].Int())
	}
	return r
}

// GlobalID returns the global identifier for the given User node.
func (u *User) GlobalID(ctx context.Context) GlobalID {
	return GlobalID{Type: typeUser, ID: fmt.Sprintf("%d", u.ID), resolvedType: u.ID}
}

// NewUserGlobalID creates a global identifier for the given User node.
func NewUserGlobalID(id int) GlobalID {
	return GlobalID{Type: typeUser, ID: fmt.Sprintf("%d", id), resolvedType: id}
}

// GlobalIDPtr returns a *GlobalID from the provided GlobalID.
func GlobalIDPtr(g GlobalID) *GlobalID {
	return &g
}

func (c *Client) FromGlobalID(ctx context.Context, r GlobalID) (_ Noder, err error) {
	defer func() {
		if IsNotFound(err) {
			err = multierror.Append(err, entgql.ErrNodeNotFound(r.String()))
		}
	}()
	switch r.Type {
	case typeUser:
		id := r.Int()
		n, err := c.User.Query().
			Where(user.ID(id)).
			CollectFields(ctx, "User").
			Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	default:
		return nil, fmt.Errorf("cannot resolve noder of type %q: %w", r.Type, errNodeInvalidID)
	}
}

func (c *Client) FromGlobalIDs(ctx context.Context, ids []*GlobalID) (_ []Noder, err error) {
	switch len(ids) {
	case 1:
		noder, err := c.FromGlobalID(ctx, *ids[0])
		if err != nil {
			return nil, err
		}
		return []Noder{noder}, nil
	case 0:
		return []Noder{}, nil
	}
	noders := make([]Noder, len(ids))
	errors := make([]error, len(ids))
	types := make(map[string][]*GlobalID)
	id2idx := make(map[GlobalID][]int, len(ids))
	for i, id := range ids {
		if id == nil {
			continue
		}
		types[id.Type] = append(types[id.Type], id)
		id2idx[*id] = append(id2idx[*id], i)
	}

	for typ, ids := range types {
		nodes, err := c.nodes(ctx, typ, ids)
		if err != nil {
			for _, id := range ids {
				for _, idx := range id2idx[*id] {
					errors[idx] = err
				}
			}
		} else {
			for i, id := range ids {
				for _, idx := range id2idx[*id] {
					noders[idx] = nodes[i]
				}
			}
		}
	}

	for i, id := range ids {
		if errors[i] == nil {
			if noders[i] != nil {
				continue
			}
			errors[i] = entgql.ErrNodeNotFound(id)
		} else if IsNotFound(errors[i]) {
			errors[i] = multierror.Append(errors[i], entgql.ErrNodeNotFound(id))
		}
		ctx := graphql.WithPathContext(ctx,
			graphql.NewPathWithIndex(i),
		)
		graphql.AddError(ctx, errors[i])
	}
	return noders, nil
}

func (c *Client) nodes(ctx context.Context, typ string, rs []*GlobalID) ([]Noder, error) {
	noders := make([]Noder, len(rs))
	switch typ {
	case typeUser:
		ids := make([]int, len(rs))
		for i := range ids {
			id := rs[i].Int()
			ids[i] = id
		}
		idmap := make(map[int][]*Noder, len(ids))
		for i, id := range ids {
			idmap[id] = append(idmap[id], &noders[i])
		}
		nodes, err := c.User.Query().
			Where(user.IDIn(ids...)).
			CollectFields(ctx, "User").
			All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	default:
		return nil, fmt.Errorf("cannot resolve noders from type %q: %w", typ, errNodeInvalidID)
	}
	return noders, nil
}
